#! /bin/bash
if [ $# -ne 1 ]; then
	echo "dist <version>"
	exit
fi

NAME="CSSBox"
VERSION="$1"
FNAME="$NAME-$VERSION"
TMPDIR="/tmp/cssbox-dist"
FDIR="$TMPDIR/$FNAME"

echo "Creating $HOME/$FNAME"
rm -rf $TMPDIR
mkdir $TMPDIR
mkdir $FDIR

cp -r src $FDIR
cp -r lib $FDIR
cp ../CSSParser/lib/antlr-runtime-3.1.jar $FDIR/lib
cp ../CSSParser/lib/slf4j-api-1.5.2.jar $FDIR/lib
cp ../CSSParser/lib/logback-classic-0.9.9.jar $FDIR/lib
cp ../CSSParser/lib/logback-core-0.9.9.jar $FDIR/lib
cp -r doc $FDIR
cp CHANGELOG COPYING COPYING.LESSER README $FDIR
(cd bin; jar cvf $FDIR/CSSBox.jar *)
(cd ../CSSParser/bin; jar cvf $FDIR/lib/jStyleParser_SNAPSHOT.jar *)

find $TMPDIR -name '.svn' -exec rm -rf {} \;

(cd $TMPDIR; zip -r $HOME/$FNAME.zip $FNAME)

#rm -rf $TMPDIR
