package org.fit.cssbox.demo;

import org.apache.commons.io.FileUtils;
import org.apache.xerces.impl.dv.util.Base64;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.xml.sax.SAXException;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;

/**
 * Class to verify the functionality of the ImageRenderer.
 *
 */
public class ImageRendererTest {

    private static final String HTML1 = "<html> <head> </head> <body> " +
                                        "<h5> Test Html </h5> " +
                                        "</body> </html>";

    private static final String BASE64_ENCODED_IMAGE = "iVBORw0KGgoAAAANSUhEUgAABLAAAAJYCAIAAAD9hIhNAAAOjElEQVR42u3ZT" +
            "0gUaBjAYUnKQ83JhMLAgsQOg5cgDxGhoSAlWGpQl5SKJfBUBCIm2j8EoyAVunSoPExE0dmIGTxFYGRY0UEp0kLCIMi0Pe3LDgzDruu2u" +
            "4XL7vOc3u91vu8wc/phwc8AAAD8LxX4CgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCA" +
            "AAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAwD8LwpaWluLi4tbW1k2bNhUUFDQ1Ne3atSuGp0+ffuPTExMT+cd" +
            "UKrV27dp4YfPmzSMjI+l0uqKiIo6rV6++fv36klf+SHd3d1zcv3+/3w8AAOD7B+HBgwcfP34cw44dO6K+7t+/H3NDQ8OTJ0++5d1MJtPc" +
            "3Pyb5d69e+Oprq6u7PHixYtxrK6uXubKksbHxwUhAADAjwrC3t7e7JAfhHfu3PmWIHz//v2WLVt+H2xNTU3x1Pnz57PHy5cvx7G+vn6ZK" +
            "0t69uyZIAQAAPhRQZiTH4Q5fX19zc3NR48evXHjRhzfvHnT1tZ24cKFlpaWa9eudXR0xJWtW7fm/hn4p0GYf2VoaGjbtm3Hjh1rb2/fsGF" +
            "DY2Pj6Ojonj17ohjv3bsnCAEAAFYsCJ8/fx6bTCYzMjJSWFj44sWLzs7OZDI5NzcX882bNycnJ5cMtmwQxoM//Wrnzp25IMy/8vbt25ij" +
            "CePBaMKYu7u7P3/+nEgktm/fLggBAABWLAjPnDkTm1OnTp08ebK0tHR4eHhgYCA2GzduHBwcXFxcXD4Il/wPYf6VmZmZmGtra2M+d+5czK" +
            "lUKuaysrKSkhJBCAAAsGJBeOjQodg8ePAg/2NXr15dv3597KMJBSEAAMB/IQgrKyujvm7fvp3bXLlyJTbHjx+PeXp6OvLs9OnTnz59+vjx" +
            "Y1VVVexfv34dH9i3b1+k3YcPH3IXGxsbY9/T05M99vf3x7Guri7m/CsvX74UhAAAACsZhAsLC319fYWFhVFfu3fvzmQy2f2XL19OnDixbt" +
            "26ioqKzs7O2Bw+fPjIkSPDw8MHDhwYGxuLTU1NTVFRUUdHx9evX7O37t69m0gk4qny8vKHDx+Ojo4mk8k4xsdu3bqVf+XSpUuxLy0tnZiY" +
            "qK6ujjkef/To0Zo1a1atWpVOp8+ePRvL6MOpqSk/IQAAwPcPwuXNzc3Nzs5m5xiiEl+9epX76/z8/Lt37/7Sg3/jCgAAACsQhAAAAAhCAA" +
            "AABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAA" +
            "BCEAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQ" +
            "QgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEA" +
            "IAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAAAQhAA" +
            "AAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAA" +
            "AhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAII" +
            "QAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAAghAAAABBCAAAgCAEA" +
            "ABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAAB" +
            "AEAIAACAIAQAAEIQAAAAIQgAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQh" +
            "AAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAIAg9BUAAAAIQgAAAAQhAAAAghAAAABBCAAAgC" +
            "AEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEA" +
            "ABAEAIAACAIAQAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQ" +
            "hAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQA" +
            "AAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAgC" +
            "AEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAA" +
            "BAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhA" +
            "AAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAABCEAAAACEIAAAAEIQAAA" +
            "IIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQ" +
            "AAAAQQgAAIAgBAAAQBACAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAAB" +
            "AEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhA" +
            "AAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAA" +
            "AhCAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAII" +
            "QAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEA" +
            "ABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAIAgBAAA" +
            "QhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhA" +
            "AAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAABCEvgIAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEA" +
            "ABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAACAIAQAAEAQAgAAIAgBAAAQ" +
            "hAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAA" +
            "AAAhCAAAABCEAAACCEAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAI" +
            "IQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAA" +
            "BAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAE" +
            "AIAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAA" +
            "AAAhCAAAABCEAAACCEAAAAEEIAACAIAQAAEAQAgAAIAgBAAAQhAAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAI" +
            "IQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAAAEIQAAAIIQAAAAQQgAAIAgBAAAQBACAAAgCAEAABCEAAAACEIAAABBCAAAgCAEA" +
            "ABAEAIAACAIAQAAEIQAAAAIQgAAAAQhAAAAghAAAABBCAAAgCAEAABAEAIAAPCv8AuMxH/OUbCHnAAAAABJRU5ErkJggg==";

    @Rule
    public TemporaryFolder temporaryFolder = new TemporaryFolder();

    /**
     * Test to verify that Images are rendered correctly.
     *
     * @throws java.io.IOException If an IO error occurs.
     * @throws org.xml.sax.SAXException If an error occurs.
     */
    @Test
    public void should_generate_the_image_correctly() throws IOException, SAXException {
        File htmlFile = temporaryFolder.newFile("test.html");
        FileUtils.writeStringToFile(htmlFile, HTML1);

        ImageRenderer imageRenderer = new ImageRenderer();
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        imageRenderer.renderURL("file://" + htmlFile.getAbsolutePath(), byteArrayOutputStream, ImageRenderer.Type.PNG);
        byte[] data = byteArrayOutputStream.toByteArray();

        Assert.assertEquals(BASE64_ENCODED_IMAGE, Base64.encode(data));
    }
}